name: Build

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:

  Build:
    runs-on: macOS-latest
    steps:
      - name: Build XCode Project
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: SampleApp.xcworkspace
          scheme: SampleApp
          destination: platform=macOS
          action: build

