name: Build

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1


  Pod Install:
    runs-on: macOS-latest
    steps:
      - name: Build XCode Project
      - runs: pod install


  Build:
    runs-on: macOS-latest
    steps:
      - name: Build XCode Project
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: SampleApp.xcworkspace
          scheme: SampleApp
          destination: platform=macOS
          action: build



