name: Swift

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force XCode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Build XCode Project
      run: swift build -v
    - name: Run Tests
      run: swift test -v
