name: Test

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:

  Build:
    runs-on: macOS-latest
    steps:
      - name: Run Unit Tests
      - run: xcodebuild test -project SampleApp.xcodeproj -scheme SampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3'
