name: Test

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:

  Build:
    runs-on: macOS-latest
    steps:
      - name: Run Unit Tests
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: SampleApp.xcodeproj
          scheme: SampleApp
          destination: platform=macOS
          action: test

